// Auth
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const SIGN_UP_FAIL = "SIGN_UP_FAIL";
export const ACTIVATION_SUCCESS = "ACTIVATION_SUCCESS";
export const ACTIVATION_FAIL = "ACTIVATION_FAIL";
export const USER_LOADED_SUCCESS = "LOAD_USER_SUCCESS";
export const USER_LOADED_FAIL = "LOAD_USER_FAIL";
export const AUTHENTICATED_SUCCESS = "AUTHENTICATED_SUCCESS";
export const AUTHENTICATED_FAIL = "AUTHENTICATED_FAIL";
export const PASSWORD_RESET_SUCCESS = "PASSWORD_RESET_SUCCESS";
export const PASSWORD_RESET_FAIL = "PASSWORD_RESET_FAIL";
export const PASSWORD_RESET_CONFIRM_SUCCESS = "PASSWORD_RESET_CONFIRM_SUCCESS";
export const PASSWORD_RESET_CONFIRM_FAIL = "PASSWORD_RESET_CONFIRM_FAIL";
export const LOGOUT = "LOGOUT";
export const LOAD_ACCOUNT_DATA = "LOAD_ACCOUNT_DATA";
export const LOAD_PERMISSIONS = "LOAD_PERMISSIONS";

export const PROFILE_LOADED_SUCCESS = "PROFILE_LOADED_SUCCESS";

// Messages
export const REMOVE_ERRORS = "REMOVE_ERRORS";
export const REMOVE_MESSAGES = "REMOVE_MESSAGES";
export const ADD_ERROR = "ADD_ERROR";
export const ADD_MESSAGE = "ADD_MESSAGE";

// Jobs
export const LOAD_JOBS = "LOAD_JOBS";
export const LOAD_MORE_JOBS = "LOAD_MORE_JOBS";

// Freelancers
export const LOAD_FREELANCERS = "LOAD_FREELANCERS";
export const LOAD_MORE_FREELANCERS = "LOAD_MORE_FREELANCERS";
